server:
  port: 7006
  servlet:
    context-path: /cdz-charging-interface
  ssl:
    key-store: classpath:3648903_www.hnjzdl.com.pfx #正式环境：3648903_www.hnjzdl.com.pfx
    key-store-password: C390RPiz #正式环境：C390RPiz
    key-store-type: PKCS12  #正式环境：PKCS12

spring:
  datasource:
    #   数据源基本配置
    username: root

    # 办公室环境
#    password: Admin@123
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.0.124:3306/carnet?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai

    # 生产环境：192.168.0.100:3306
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.100:3306/carnet?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai


    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 127.0.0.1    # 192.168.0.199 办公室   #39.104.60.18 鹏鸟云   # 景郑8000服务器 127.0.0.1
    port: 6379
#    password: 198401
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
    timeout: 100000

  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:com/pengniao/cdzcharginginterface/mapper/xml/*.xml
  typeAliasesPackage: com.pengniao.cdzcharginginterface.entity

custom-parameters:
#  kuaidian-request: http://192.168.0.113:8099/kuaidian-interface/evcs/v1.1/   # 办公室

  kuaidian-request: http://211.142.201.26:8099/kuaidian-interface/evcs/v1.1/   # 正式环境
